services:
  database:
    build:
      context: ./database
    volumes:
      - db-data:/opt/oracle/oradata
    ports:
      - "${DB_PORT:-1521}:1521"
    environment:
      - ORACLE_PDB=${ORACLE_PDB:-MEDPDB}
      - ORACLE_PWD=${ORACLE_PWD:-12345}
    networks:
      - medical-network
    healthcheck:
      test: ["CMD", "sqlplus", "-s", "system/${ORACLE_PWD}@//localhost:1521/${ORACLE_PDB}", "<<< 'SELECT 1 FROM DUAL;'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 80s

  backend:
    build:
      context: https://github.com/Actividades-Arqui-2510/P1-Backend.git
      args:
        - ORACLE_PDB=${ORACLE_PDB:-MEDPDB}
        - ORACLE_PWD=${ORACLE_PWD:-12345}
        - DB_PORT=${DB_PORT:-1521}
        - DB_USER=${DB_USER:-medadmin}
        - DB_PASSWORD=${DB_PASSWORD:-12345}
        - DB_HOST=database
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=${DB_PORT:-1521}
      - DB_USER=${DB_USER:-medadmin}
      - DB_PASSWORD=${DB_PASSWORD:-12345}
      - ORACLE_PDB=${ORACLE_PDB:-MEDPDB}
      - ORACLE_PWD=${ORACLE_PWD:-12345}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - medical-network

networks:
  medical-network:
    driver: bridge

volumes:
  db-data:
    driver: local