services:
  database:
    build:
      context: ./database
    volumes:
      - db-data:/opt/oracle/oradata
    ports:
      - "${DB_PORT:-1521}:1521"
    environment:
      - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
      - ORACLE_PDB=${ORACLE_PDB:-MEDPDB}
      - ORACLE_PWD=${ORACLE_PWD:-12345}
      - DB_USER=${DB_USER:-medadmin}
      - DB_PASSWORD=${DB_PASSWORD:-12345}
      - DB_PORT=${DB_PORT:-1521}
    networks:
      - medical-network
    healthcheck:
      test: ["CMD", "/database/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 80s

  backend:
    build:
      context: https://github.com/Actividades-Arqui-2510/P1-Backend.git#v1.0.0
      args:
        - ORACLE_PDB=${ORACLE_PDB:-MEDPDB}
        - ORACLE_PWD=${ORACLE_PWD:-12345}
        - DB_PORT=${DB_PORT:-1521}
        - DB_USER=${DB_USER:-medadmin}
        - DB_PASSWORD=${DB_PASSWORD:-12345}
        - DB_HOST=database
    ports:
      - "${BACKEND_PORT:-8080}:8080"
      - "4848:4848"
    environment:
      - DB_HOST=database
      - DB_PORT=${DB_PORT:-1521}
      - DB_USER=${DB_USER:-medadmin}
      - DB_PASSWORD=${DB_PASSWORD:-12345}
      - ORACLE_PDB=${ORACLE_PDB:-MEDPDB}
      - ORACLE_PWD=${ORACLE_PWD:-12345}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - medical-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/soap/users?wsdl"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  frontend:
    build:
      context: https://github.com/Actividades-Arqui-2510/P1-Front.git#v1.0.0
      args:
        - VITE_DOCKER_ENV=true
        - VITE_API_URL=http://localhost:8080/soap
    ports:
      - "3000:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - medical-network

networks:
  medical-network:
    driver: bridge

volumes:
  db-data:
    driver: local
